workflows:
  aar-build:
    name: Build Moonlight AAR
    scripts:
      - name: Build Debug AAR
        script: |
          ./gradlew :xrstreamingplugin:assembleDebug
    artifacts:
      - xrstreamingplugin/build/outputs/aar/*.aar
