workflows:
  aar-build:
    name: Build Moonlight AAR
    scripts:
      - name: Build and Extract
        script: |
          # Just build everything and see what we get
          ./gradlew build --continue
      - name: Collect All Outputs
        script: |
          echo "=== All build outputs ==="
          find . -name "*.aar" -type f
          find . -name "*.apk" -type f  
          find . -name "*.jar" -type f
    artifacts:
      - "**/*.aar"
      - "**/*.apk"
      - "build/**/*"
