workflows:
  aar-build:
    name: Build Moonlight AAR for Unity
    scripts:
      - name: Debug Build Issues
        script: |
          echo "=== Project Structure ==="
          find . -name "*.java" -path "*/xrstreamingplugin/*" | head -20
          echo "=== MoonlightBridge content ==="
          cat xrstreamingplugin/src/main/java/com/example/moonlight/MoonlightBridge.java || echo "File not found"
          echo "=== MoonlightXRPlugin content ==="
          find . -name "MoonlightXRPlugin.java" -exec cat {} \; || echo "File not found"
      - name: Try Building
        script: |
          ./gradlew :xrstreamingplugin:assembleDebug --stacktrace
    artifacts:
      - xrstreamingplugin/build/outputs/aar/*.aar
