
workflows:
  aar-build:
    name: Build Moonlight AAR for Unity
    scripts:
      - name: Fix BuildConfig Dependencies
        script: |
          # Replace BuildConfig references with hardcoded values in ALL problematic files
          sed -i 's/BuildConfig\.DEBUG/true/g' app/src/main/java/com/limelight/binding/video/MediaCodecDecoderRenderer.java
          sed -i 's/BuildConfig\.DEBUG/false/g' app/src/main/java/com/limelight/nvstream/http/NvHTTP.java
          sed -i 's/BuildConfig\.APPLICATION_ID/"com.limelight"/g' app/src/main/java/com/limelight/PosterContentProvider.java
          sed -i 's/BuildConfig\.ROOT_BUILD/false/g' app/src/main/java/com/limelight/binding/input/capture/InputCaptureManager.java
          sed -i 's/BuildConfig\.ROOT_BUILD/false/g' app/src/main/java/com/limelight/binding/input/evdev/EvdevCaptureProviderShim.java
          
          # Also fix the interface implementation issue in MoonlightXRPlugin
          # Remove the @Override annotation from the problematic method
          sed -i 's/@Override//' xrstreamingplugin/src/main/java/com/limelight/xr/MoonlightXRPlugin.java
      - name: Build AAR
        script: |
          ./gradlew :xrstreamingplugin:assembleDebug
      - name: Verify AAR
        script: |
          echo "=== Generated AAR files ==="
          find . -name "*.aar" -type f
    artifacts:
      - xrstreamingplugin/build/outputs/aar/*.aar
