workflows:
  aar-build:
    name: Build Moonlight AAR for Unity
    scripts:
      - name: Fix BuildConfig with Python
        script: |
          # Use Python to fix the files (more reliable than sed)
          python3 << 'EOF'
          import fileinput
          import glob
          import os
          
          # Fix all Java files in app module
          for file_path in glob.glob("app/src/main/java/**/*.java", recursive=True):
              with fileinput.FileInput(file_path, inplace=True) as file:
                  for line in file:
                      line = line.replace("BuildConfig.DEBUG", "true")
                      line = line.replace("BuildConfig.ROOT_BUILD", "false") 
                      line = line.replace('BuildConfig.APPLICATION_ID', '"com.limelight"')
                      print(line, end='')
          
          # Fix the specific @Override issue
          with fileinput.FileInput("xrstreamingplugin/src/main/java/com/limelight/xr/MoonlightXRPlugin.java", inplace=True) as file:
              lines = list(file)
              if len(lines) >= 233:
                  lines[232] = lines[232].replace("@Override", "")
              for line in lines:
                  print(line, end='')
          EOF
      - name: Build AAR
        script: |
          ./gradlew :xrstreamingplugin:assembleDebug
    artifacts:
      - xrstreamingplugin/build/outputs/aar/*.aar
