workflows:
  aar-build:
    name: Build Moonlight AAR for Unity
    scripts:
      - name: Build All Dependencies
        script: |
          # First build the app module to generate ALL BuildConfig and dependencies
          ./gradlew :app:compileDebugJavaWithJavac
          # Then build the AAR module
          ./gradlew :xrstreamingplugin:assembleDebug
      - name: List Output Files
        script: |
          find . -name "*.aar" -type f
          find . -name "BuildConfig.java" -type f
    artifacts:
      - xrstreamingplugin/build/outputs/aar/*.aar
