workflows:
  apk-build:
    name: Build Moonlight APK
    scripts:
      - name: Build APK
        script: |
          ./gradlew :app:assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
